# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Install python3, pip and create a symlink for python
RUN apk add --no-cache python3 py3-pip && ln -sf python3 /usr/bin/python

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json if they exist
COPY package*.json ./

# Install Node.js dependencies (ignoring postinstall scripts if necessary)
RUN npm install --ignore-scripts

# Copy requirements and install Python dependencies with --break-system-packages
COPY requirements.txt ./
RUN pip install --no-cache-dir --break-system-packages -r requirements.txt

# Copy the rest of the application code
COPY . .

# Default command: start the MCP server via npm
CMD ["npm", "start"]
